sudo: required

language: bash
services: docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - sudo curl -L https://raw.githubusercontent.com/metowolf/docker-builder/master/scripts/publish.sh -o /usr/local/bin/docker-publish
  - sudo chmod +x /usr/local/bin/docker-publish

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t travis .
      if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        image_version=`cat package.json | grep 'version' | awk -F '"' '{print $4}'`
        if [ ! "$TRAVIS_BRANCH" = "master" ]; then
          image_version="${image_version}-dev"
        fi
        docker-publish travis metowolf/bilibilihelper:${image_version} 2
      fi
    )
after_script:
  - docker images
